import "./globals.css";

import { polyfill } from "interweave-ssr";
import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";

import { cx } from "@/lib/cva.config";

import { ThemeProvider } from "./theme-provider";

polyfill();

const fontSans = Work_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cx(
        "h-full bg-background text-on-background antialiased",
        fontSans.variable
      )}
    >
      <body className="h-full">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
